import Exception from 'Runtime/Exception';

describe('Runtime/Exception', () => {

    describe('Constructor:', () => {

        xit('Has no facts.', () => {});

    });

    describe('Methods:', () => {

        describe('create', () => {

            xit('Has no facts.', () => {});

        });

        describe('deserialize', () => {

            xit('Has no facts.', () => {});

        });

    });

});
